spring.application.name=jobapp

spring.mvc.view.suffix=/views/
spring.mvc.view.prefix=.jsp

spring.datasource.url= jdbc:postgresql://localhost:5432/talha
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

